### ISSUE TITLE
PDF?

### ISSUE THREAD

**Issue by palaslet** [tkbletsc/ksp-science-checklist#4]
Would you mind update the PDF export?
My Py is a bit rusty, and I'd really like this sheet for 1.0. I used it for .23, but a lot has happened since then :)

**Comment by tkbletsc** [comment]
Unfortunately, I'm not playing KSP at the moment, and I don't have time or
up to date game knowledge to make the revisions.

There was another guy doing updates on a fork, and I've accepted every pull
request he made. I don't think he finished though, but you're welcome to
pike through his findings, and if you take up the gauntlet, I'd definitely
support you.

Sorry I couldn't be more help.
- Tyler (sent from a phone)
